export const CHANGE_MATH_INPUT = 'CHANGE_MATH_INPUT';
export const CHANGE_MATH_EXPRESSION = 'CHANGE_MATH_EXPRESSION';
export const SET_RANDOM_MATH_EXPRESSION = 'SET_RANDOM_MATH_EXPRESSION';
export const CREATE_CHILD_MATH_TASK = 'CREATE_CHILD_MATH_TASK';
