export const CHANGE_MATH_INPUT = 'CHANGE_MATH_INPUT';
export const CHANGE_MATH_EXPRESSION = 'CHANGE_MATH_EXPRESSION';
export const SET_RANDOM_MATH_CHAIN_EXPRESSION = 'SET_RANDOM_MATH_CHAIN_EXPRESSION';
export const SET_RANDOM_MATH_ADD_EXPRESSION = 'SET_RANDOM_MATH_ADD_EXPRESSION';
export const SET_RANDOM_MATH_COMMON_EXPRESSION = 'SET_RANDOM_MATH_COMMON_EXPRESSION';
export const SET_RANDOM_MATH_PROD_EXPRESSION = 'SET_RANDOM_MATH_PROD_EXPRESSION';
export const SET_RANDOM_MATH_INVERSE_EXPRESSION = 'SET_RANDOM_MATH_INVERSE_EXPRESSION';
export const CREATE_CHILD_MATH_TASK = 'CREATE_CHILD_MATH_TASK';
export const SET_MATH_EXPRESSION_TO_PARENT_TASK = 'SET_MATH_EXPRESSION_TO_PARENT_TASK';
export const SELECT_DIFF_TABLE_ITEM = 'SELECT_DIFF_TABLE_ITEM';

export const SET_RANDOM_BOOL_TABLE_FORMULA = 'SET_RANDOM_BOOL_TABLE_FORMULA';
export const SET_RANDOM_BOOL_EQUAL_FORMULA = 'SET_RANDOM_BOOL_EQUAL_FORMULA';
export const UPDATE_BOOL_TABLE_ANSWER = 'UPDATE_BOOL_TABLE_ANSWER';
export const UPDATE_BOOL_EVAL_ANSWER = 'UPDATE_BOOL_EVAL_ANSWER';
export const SET_BOOL_CHILD_TASK = 'SET_BOOL_CHILD_TASK';
export const SET_BOOL_FORMULA_TO_PARENT_TASK = 'SET_BOOL_FORMULA_TO_PARENT_TASK';
export const SET_DONE_EQUAL = 'SET_DONE_EQUAL';


export const LOAD_MORE_TESTS         = 'LOAD_MORE_TESTS';
export const LOAD_MORE_TESTS_STARTED = 'LOAD_MORE_TESTS_STARTED';
export const LOAD_MORE_TESTS_SUCCESS = 'LOAD_MORE_TESTS_SUCCESS';
export const LOAD_MORE_TESTS_ERROR   = 'LOAD_MORE_TESTS_ERROR';

export const TEST_START = 'TEST_START';
export const TEST_START_STARTED = 'TEST_START_STARTED';
export const TEST_START_SUCCESS = 'TEST_START_SUCCESS';
export const TEST_START_ERROR = 'TEST_START_ERROR';

export const TEST_ANSWER = 'TEST_ANSWER';
export const TEST_NEXT_QUESTION = 'TEST_NEXT_QUESTION';
